spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planner?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: planner
    password: planner
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: 8080
