spring:
  profiles:
    default: dev

jwt:
  secret: ${JWT_SECRET:change-me-super-secret-32chars}
  expirationMinutes: 30
  refreshExpirationDays: 7
logging:
  level:
    org.springframework.security: DEBUG
    adonis.planner.security: DEBUG
